### ISSUE TITLE
An issue occurred trying to dump the memory to a file

### ISSUE THREAD

**Issue by QuestionGuy** [strazzere/android-unpacker#32] opened 2017-04-01 21:14 UTC
Steps to reproduce:
1. trying to unpack this: https://play.google.com/store/apps/details?id=com.zhiliaoapp.musicallylite
2. ./data/local/tmp/kisskiss com.zhiliaoapp.musicallylite

[Screenshot](http://image.prntscr.com/image/53d561756e514aab8f06f0e44b264792.png
)

Using:
Nox Player (x86)
API Version 19 (4.4.2)

> SHA1: 0c4d6be2dc5de92bcb0a87b2bcd4108a7634d0a6

**Comment by QuestionGuy** [comment] 2017-04-02 10:05
Adding this line of code before return -1:

`printf(" [!] error: %s\n", strerror(errno));`

prints:

> error: Invalid Argument

**Comment by dinekro** [comment] 2017-08-28 18:31
I have the same problem. "pread" returns -1 everywhere and  errno == 22 (Invalid Argument)
This is the same for any running process in the system.
API Version 22 (5.1.1) x86 Android Emulator

Screen with some log info:
![image](https://user-images.githubusercontent.com/7703735/29787511-e658104a-8c37-11e7-9cf4-ee1cf4a503c3.png)

**Comment by strazzere** [comment] 2017-08-28 18:54
Are you using the same application? Judging by the man page for `Invalid argument`;

```
EINVAL
The STREAM or multiplexer referenced by fildes is linked (directly or indirectly) downstream from a multiplexer.
```

The application is potentially already reading the address or has it locked some way.

Based on your screen shot, it looks like the unpacker is attempting to read protected or non-readable areas. Try unprotecting/enabling reading fish.

**Comment by dinekro** [comment] 2017-08-28 19:07
I use your native-unpacker (kisskiss), last version (current master brunch), by the way it's very good solution.
I see, that pread not work properly for me.
How can i try unprotecting/enabling reading?
I run the app by root, of couse.

**Comment by strazzere** [comment] 2017-08-28 19:43
Currently the code doesn't do anything to the memory regions - so it needs to be changed within the code.

Do you have the application hash you're attempting to unpack? Or potentially an uploaded file?

**Comment by dinekro** [comment] 2017-08-28 20:20
SHA1: 5EA79666EF98D70B2673FE8885181CEBB30AA8EC

But i don't thinks this problem connected with app. 
I think the cause of the problem is in the emulator or OS. I'm going to try unpuck it on other version of android.

**Comment by strazzere** [comment] 2017-08-28 20:22
Cool, let me know if that helps. Since you're running on 5 or higher, selinux might be nerfing ptrace/pread/etc.

**Comment by dinekro** [comment] 2017-08-28 20:35
Android 7: all the same...
May be the cause of the problem is the emulator. I use the original google AVD.
![image](https://user-images.githubusercontent.com/7703735/29792565-72c04a5a-8c49-11e7-8068-83016ae86987.png)

**Comment by strazzere** [comment] 2017-08-28 23:18
What makes you believe this application is packed? It does not appear to be, though it does include some obfuscation and protectors.

**Comment by dinekro** [comment] 2017-08-28 23:33
Two parts of signing and encrypt/decrypt mechanism is packed. But very simple, without encryption.
Getting a model of classes from memory can would be nice. But I found it now, without unpacking.
Thank you. I think, i have solved my task.

**Comment by strazzere** [comment] 2017-08-28 23:43
I've only skimmed the binary, it appears two dex files are dynamically loaded (they're listed as shared libraries via extensions, but are just jar's)

Other than that didn't see anything "packed". Going to close this for now.

**Closed by strazzere** 2017-08-28 23:43 UTC
