### ISSUE TITLE
Error unpack plz help me

### ISSUE THREAD

**Issue by aliheidari020** [strazzere/android-unpacker#26] opened 2016-11-01 15:19 UTC
Hi
pread seems to have failed!
an issue occurred trying to dump the memory to a file!
https://s21.postimg.org/899408yif/Untitled2.png

**Comment by CalebFenton** [comment] 2016-11-01 17:33
There's absolutely no way to reproduce -> understand -> fix your issue without at least the hash of the file that you're trying to dump. Post the hash please.

**Comment by amanaksu** [comment] 2016-11-02 14:39
You probably do not have read access to that memory.
I also have the same problem.
Should AVD be routed?
Or do you know the malicious Hash that works normally?
Hash : 1f1db090d4f81d75cc4188c895bc0ba5be460db9fc1553d4729a857bd9f487cc

**Comment by aliheidari020** [comment] 2016-11-02 15:20
Yes my android device is routed
I do not know hash!

**Comment by amanaksu** [comment] 2016-11-02 15:22
It is recommended to dump using gdb.

**Comment by strazzere** [comment] 2018-01-27 23:36
Closing this since the issues are conflating multiple things and only for support vs bug/enhancement.

**Closed by strazzere** 2018-01-27 23:36 UTC
